name: Furminal Documentation

on:
  push:
    branches: [ "release/v*" ]

jobs:
  doc:
    permissions:
      id-token: write
      pages: write

    runs-on: windows-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install docfx
      run: |
        dotnet tool update -g docfx

    - name: Install powershell-yaml
      run: |
        Install-Module -AcceptLicense -Force powershell-yaml

    - name: Build documentation
      run: |
        pwsh .\docs\docgen\New-Docfx-Site.ps1

    - name: Upload documentation
      uses: actions/upload-pages-artifact@v3
      with:
        name: furminal-documentation
        path: ./docs/docgen/_site
        retention-days: 1

    - name: Publish documentation
      uses: actions/deploy-pages@v4
      with:
        artifact_name: furminal-documentation
