# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will build, test, sign and package a WPF or Windows Forms desktop application
# built on .NET Core.
# To learn how to migrate your existing application to .NET Core,
# refer to https://docs.microsoft.com/en-us/dotnet/desktop-wpf/migration/convert-project-from-net-framework
#
# To configure this workflow:
#
# 1. Configure environment variables
# GitHub sets default environment variables for every workflow run.
# Replace the variables relative to your project in the "env" section below.
#
# 2. Signing
# Generate a signing certificate in the Windows Application
# Packaging Project or add an existing signing certificate to the project.
# Next, use PowerShell to encode the .pfx file using Base64 encoding
# by running the following Powershell script to generate the output string:
#
# $pfx_cert = Get-Content '.\SigningCertificate.pfx' -Encoding Byte
# [System.Convert]::ToBase64String($pfx_cert) | Out-File 'SigningCertificate_Encoded.txt'
#
# Open the output file, SigningCertificate_Encoded.txt, and copy the
# string inside. Then, add the string to the repo as a GitHub secret
# and name it "Base64_Encoded_Pfx."
# For more information on how to configure your signing certificate for
# this workflow, refer to https://github.com/microsoft/github-actions-for-desktop-apps#signing
#
# Finally, add the signing certificate password to the repo as a secret and name it "Pfx_Key".
# See "Build the Windows Application Packaging project" below to see how the secret is used.
#
# For more information on GitHub Actions, refer to https://github.com/features/actions
# For a complete CI/CD sample to get started with GitHub Action workflows for Desktop Applications,
# refer to https://github.com/microsoft/github-actions-for-desktop-apps

name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:

  build:
    strategy:
      matrix:
        platform: [ARM64]
        configuration: [Release]
    runs-on: windows-latest

    env:
      Solution_Name: Furminal.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    # Get license information
    #- name: Get licenses
    #  working-directory: ./LICENSES
    #  run: pwsh .\licensegen\Get-Licenses.ps1

    # Install vswhere
    #- name: Install vswhere
    #  run: winget install vswhere --disable-interactivity --accept-source-agreements --accept-package-agreements
    
    # Restore NuGet packages
    - name: Restore NuGet packages
      run: msbuild $env:Solution_Name -t:restore /p:Platform=$env:Platform /p:Configuration=$env:Configuration
      env:
        Platform: ${{ matrix.platform }}
        Configuration: ${{ matrix.configuration }}
      
    # Build the application
    - name: Build the application
      run: msbuild $env:Solution_Name /p:Platform=$env:Platform /p:Configuration=$env:Configuration
      env:
        Platform: ${{ matrix.platform }}
        Configuration: ${{ matrix.configuration }}

    # Decode the base 64 encoded pfx and save the Signing_Certificate
    - name: Decode the certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.FURMINAL_CERTIFICATE }}")
        [IO.File]::WriteAllBytes("GitHubActionsWorkflow.pfx", $pfx_cert_byte)

    # Create the app package
    - name: Create the app package
      run: msbuild $env:Solution_Name /p:Platform=$env:Platform /p:Configuration=$env:Configuration /p:GenerateAppxPackageOnBuild=true /p:PackageCertificateKeyFile=..\GitHubActionsWorkflow.pfx
      env:
        Platform: ${{ matrix.platform }}
        Configuration: ${{ matrix.configuration }}

    # Remove the pfx
    - name: Remove the certificate
      run: Remove-Item -Force -Path GitHubActionsWorkflow.pfx

    # Locate the MSIX package
    - name: Locate MSIX package
      id: locate_msix_package
      run: |
        $msix = Get-ChildItem -Recurse -Path . -Filter "*.msix" |
                Where-Object { $_.FullName -like "*AppPackages*" } |
                Select-Object -First 1 -ExpandProperty FullName
        echo "package=$($msix.FullName) >> $env:GITHUB_OUTPUT

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload MSIX package
      uses: actions/upload-artifact@v4
      with:
        name: MSIX Package
        path: ${{ steps.locate_msix_package.outputs.package }}
