name: Furminal CI/CD

on:
  push:
    branches: [ "main", "release/v*" ]
    tags: [ "v*" ]

permissions:
  contents: write

permissions:
  contents: write

jobs:

  version_only:
    runs-on: ubuntu-latest

    outputs:
      skip_build: ${{ steps.check_for_version.outputs.skip_build }}
      skip_reason: ${{ steps.check_for_version.outputs.skip_reason }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Check for version.json only
      id: check_for_version
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -qv "^version\.json$"; then
          echo "skip_build=false" >> $GITHUB_OUTPUT
          echo "Proceeding with build."
        else
          echo "skip_build=true" >> $GITHUB_OUTPUT
          echo "skip_reason=Only version.json changed" >> $GITHUB_OUTPUT
          echo "Skipping build."
        fi

  build:
    if: needs.version_only.outputs.skip_build == 'false'

    strategy:
      matrix:
        platform: [x64, ARM64]
        configuration: [Release]
        include:
          - platform: x64
            runs_on: windows-latest
          - platform: ARM64
            runs_on: windows-11-arm

    runs-on: ${{ matrix.runs_on }}

    env:
      Solution_Name: Furminal.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Get NuGetLicenseFramework
      run: |
        Invoke-WebRequest -Uri "https://github.com/sensslen/nuget-license/releases/download/v3.1.6/release.zip" -OutFile NuGetLicense.zip
        Expand-Archive -Path NuGetLicense.zip -DestinationPath NuGetLicense

    - name: Restore NuGet packages
      run: msbuild $env:Solution_Name -t:restore /p:Platform=$env:Platform /p:Configuration=$env:Configuration
      env:
        Platform: ${{ matrix.platform }}
        Configuration: ${{ matrix.configuration }}

    - name: Build application
      run: msbuild $env:Solution_Name /p:Platform=$env:Platform /p:Configuration=$env:Configuration
      env:
        Platform: ${{ matrix.platform }}
        Configuration: ${{ matrix.configuration }}

    - name: Get licenses
      working-directory: ./LICENSES
      run: pwsh .\licensegen\Get-Licenses.ps1

    - name: Decode certificate
      run: |
        $pfx_cert_byte = [System.Convert]::FromBase64String("${{ secrets.FURMINAL_CERTIFICATE }}")
        [IO.File]::WriteAllBytes("GitHubActionsWorkflow.pfx", $pfx_cert_byte)

    - name: Create app package
      run: msbuild $env:Solution_Name /p:Platform=$env:Platform /p:Configuration=$env:Configuration /p:GenerateAppxPackageOnBuild=true /p:PackageCertificateKeyFile=..\GitHubActionsWorkflow.pfx
      env:
        Platform: ${{ matrix.platform }}
        Configuration: ${{ matrix.configuration }}

    - name: Remove certificate
      run: Remove-Item -Force -Path GitHubActionsWorkflow.pfx

    - name: Locate MSIX package
      id: locate_msix_package
      run: |
        $msix = Get-ChildItem -Recurse -Path . -Filter "*.msix" |
                Where-Object { $_.FullName -like "*AppPackages*" } |
                Select-Object -First 1 -ExpandProperty FullName
        Write-Host "Located package: $msix"
        "package=$msix" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Upload MSIX packages
      uses: actions/upload-artifact@v4
      with:
        name: msix-package-${{ matrix.platform }}-${{ matrix.configuration }}
        path: ${{ steps.locate_msix_package.outputs.package }}
        retention-days: 1

  release:
    needs: build

    runs-on: ubuntu-latest

    if: |
      github.ref_type == 'tag' &&
      startsWith(github.ref, 'refs/tags/v') &&
      (github.base_ref == '' || startsWith(github.base_ref, 'release/v'))

    steps:
    - name: Download MSIX packages
      uses: actions/download-artifact@v4
      with:
        name: msix-package-${{ matrix.platform }}-${{ matrix.configuration }}

    - name: Publish release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: "Furminal ${{ github.ref_name }}"
        files: "**/*.msix"
        generate_release_notes: true
        make_latest: "true"

  skip_report:
    needs: version_only

    runs-on: ubuntu-latest

    if: needs.version_only.outputs.skip_build == 'true'

    steps:
      - name: Report skip reason
        run: |
          echo "⚡ Build skipped: ${{ needs.version_only.outputs.skip_reason }}"
